### ISSUE TITLE
wish: per method documentation

### ISSUE THREAD

**Issue by markstos** [tschaub/authorized#6]
Thanks for this software. I'm evaluating it and it looks useful. 

The examples provided in the documentation are nice, but  per-method documentation would be a welcome addition to the documentation-- for example, explicitly spelling out the inputs and return value of the done() method.

**Comment by markus138** [comment]
We're going to try a node.js lib for authorization this week and this one seems to be just what we've been looking for. Do you have any update on the documentation?

**Comment by tschaub** [comment]
Thanks for your interest.  I've added API docs to the readme and published [`authorized@1.0.0`](https://www.npmjs.com/package/authorized).  Let me know if anything is unclear or if you encounter any issues.

**Comment by markstos** [comment]
The docs looks great. Thank you!

**Comment by markus138** [comment]
Thank you very much! We started using the lib today!
